### PR TITLE
Add mentions of JSON requirement and Docker Hub

### PR DESCRIPTION
**Pull request by rgauss**
See #87

### CODE REVIEW

**Comment by kylelaker** [comment]
Do we want to link to https://github.com/usnistgov/OSCAL/tree/main/json/convert?

**Comment by rgauss** [comment]
> Do we want to link to https://github.com/usnistgov/OSCAL/tree/main/json/convert?

Sure, added.

**Comment by rgauss** [comment]
Looks like builds are failing due to EasyDynamics/oscal-react-library#398.

**Comment by kylelaker** [comment]
I tried to re-run the checks on this branch but I think maybe this needs to be rebased on `main` (or have `main` merged into it)

**Review by laurelmay — APPROVED** [review]

**Review by tuckerzp — APPROVED** [review]

**Pull request merged**
