### PR TITLE
Adjust Cypress Testing to `Move Rest Mode Icon`

### PR DESCRIPTION
**Pull request by Bronstrom**
This addresses testing to fit [oscal-react-library #494](https://github.com/EasyDynamics/oscal-react-library/pull/494). The only major change to cypress testing is a single line to remove the hamburger icon click, as the drawer selector opens automatically now.

This won't pass until [oscal-react-library #494](https://github.com/EasyDynamics/oscal-react-library/pull/494) is merged.

### CODE REVIEW

**Comment by Bronstrom** [comment]
There were a couple other miscellaneous changes I made as well including an invalid api path route (missing an 's'), the wrong profile being checked, and an unused constant.

**Comment by Bronstrom** [comment]
To less the amount of intermittent failing happening when testing catalog, I've extended `wait()` times.

**Comment by tuckerzp** [comment]
So I think that the failures are still due to the catalog being large and not an issue with the navigation changing anymore.

**Review by tuckerzp — APPROVED** [review]
I am very glad to see the tests go back to green again. I am not entirely convinced that this will permanently fix intermittent failures, but it is certainly better than it was.

**Review by kylelaker — APPROVED** [review]

**Pull request merged**
